version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 6831:6831/udp
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    command: ["--log-level=debug"]

  # datadog-agent:
  #   image: gcr.io/datadoghq/agent:7
  #   environment:
  #     DD_APM_ENABLED: "true"
  #     DD_APM_NON_LOCAL_TRAFFIC: "true"
  #     DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
  #     DD_API_KEY: 4d2ab0ad74aa1a3042134fffc99dc12b
  #     # DD_HOSTNAME: datadog.vhorodnii.com


volumes:
  rabbitmq_data: